const WHITE_RICE = 'WHITE_RICE';
const BROWN_RICE = 'BROWN_RICE';
const KALE = 'KALE';
const BABY_SPINACH = 'BABY_SPINACH';
const CHICKPEAS = 'CHICKPEAS';
const LENTILS = 'LENTILS';
const MESCLUN_LETTUCE = 'MESCLUN_LETTUCE';
const ROMANIE_LETTUCE = 'ROMANIE_LETTUCE';
const ROTINI_PASTA = 'ROTINI_PASTA';
const FARFELLE_PASTA = 'FARFELLE_PASTA';
const QUINOA = 'QUINOA';
const COUSCOUS = 'COUSCOUS';
const WILD_ROCKET = 'WILD_ROCKET';

export default [
  WHITE_RICE,
  BROWN_RICE,
  KALE,
  BABY_SPINACH,
  CHICKPEAS,
  LENTILS,
  MESCLUN_LETTUCE,
  ROMANIE_LETTUCE,
  ROTINI_PASTA,
  FARFELLE_PASTA,
  QUINOA,
  COUSCOUS,
  WILD_ROCKET,
];
