const PESTO = 'PESTO';
const SPICY = 'SPICY';
const SALAD_MARKET = 'SALAD_MARKET';
const HONEY = 'HONEY';
const TAPENADE = 'TAPENADE';
const RASPBERRY_SAUCE = 'RASPBERRY_SAUCE';
const CLASSIC = 'CLASSIC';
const VINEGAR_CREAM = 'VINEGAR_CREAM';
const SOY_SAUCE = 'SOY_SAUCE';
const YOGHURT = 'YOGHURT';
const PINK_SAUCE = 'PINK_SAUCE';
const CAESAR = 'CAESAR';
const MUSTARD_AND_HONEY = 'MUSTARD_AND_HONEY';
const MANGO = 'MANGO';
const LEMON = 'LEMON';
const NONE = 'NONE';

export default [
  SPICY,
  PESTO,
  SALAD_MARKET,
  HONEY,
  TAPENADE,
  RASPBERRY_SAUCE,
  CLASSIC,
  VINEGAR_CREAM,
  SOY_SAUCE,
  YOGHURT,
  PINK_SAUCE,
  CAESAR,
  MUSTARD_AND_HONEY,
  MANGO,
  LEMON,
  NONE,
];
