const TUNA = 'TUNA';
const AVOCADO = 'AVOCADO';
const CRANBERRY = 'CRANBERRY';
const BROCCOLI = 'BROCCOLI';
const SOY_SPROUTS = 'SOY_SPROUTS';
const WHITE_ONION = 'WHITE_ONION';
const COMMON_MUSHROOM = 'COMMON_MUSHROOM';
const WHITE_ASPARAGUS = 'WHITE_ASPARAGUS';
const POMEGRANATE = 'POMEGRANATE';
const BOILED_EGG = 'BOILED_EGG';
const SWEET_CORN = 'SWEET_CORN';
const MIXED_NUTS = 'MIXED_NUTS';
const WALNUTS = 'WALNUTS';
const GREEN_OLIVES = 'GREEN_OLIVES';
const BLACK_OLIVES = 'BLACK_OLIVES';
const RAISINS = 'RAISINS';
const PINEAPPLE = 'PINEAPPLE';
const TURKEY = 'TURKEY';
const CROUTONS = 'CROUTONS';
const BRAISED_CHICKEN = 'BRAISED_CHICKEN';
const FETA_DICED_CHEESE = 'FETA_DICED_CHEESE';
const MOZZARELLA_PEARLS_CHEESE = 'MOZZARELLA_PEARLS_CHEESE';
const PARMESAN_CHEESE = 'PARMESAN_CHEESE';
const EMMENTAL_CHEESE = 'EMMENTAL_CHEESE';
const PUMPKIN_SEEDS = 'PUMPKIN_SEEDS';
const SUNFLOWER_SEEDS = 'SUNFLOWER_SEEDS';
const CHERRY_TOMATOES = 'CHERRY_TOMATOES';
const CARROT = 'CARROT';
const QUAIL_EGGS = 'QUAIL_EGGS';
const LARGE_STRAWBERRIES = 'LARGE_STRAWBERRIES';
const CRAB_STICKS = 'CRAB_STICKS';
const IMITATION_ELVERS = 'IMITATION_ELVERS';
const APPLE = 'APPLE';

export default [
  TUNA,
  AVOCADO,
  CRANBERRY,
  BROCCOLI,
  SOY_SPROUTS,
  WHITE_ONION,
  COMMON_MUSHROOM,
  WHITE_ASPARAGUS,
  POMEGRANATE,
  BOILED_EGG,
  SWEET_CORN,
  MIXED_NUTS,
  WALNUTS,
  GREEN_OLIVES,
  BLACK_OLIVES,
  RAISINS,
  PINEAPPLE,
  TURKEY,
  CROUTONS,
  BRAISED_CHICKEN,
  FETA_DICED_CHEESE,
  MOZZARELLA_PEARLS_CHEESE,
  PARMESAN_CHEESE,
  EMMENTAL_CHEESE,
  PUMPKIN_SEEDS,
  SUNFLOWER_SEEDS,
  CHERRY_TOMATOES,
  CARROT,
  QUAIL_EGGS,
  LARGE_STRAWBERRIES,
  CRAB_STICKS,
  IMITATION_ELVERS,
  APPLE,
];
